# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 18:57
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myclosetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=255)),
                ('image_path', models.ImageField(blank=True, upload_to='images/')),
                ('item_category', models.ForeignKey(choices=[('outerwear', 'OUTERWEAR'), ('tops', 'TOPS'), ('bottoms', 'BOTTOMS'), ('dresses', 'DRESSES'), ('bags', 'BAGS'), ('shoes', 'SHOES'), ('accessories', 'ACCESSORIES')], on_delete=django.db.models.deletion.CASCADE, to='myclosetapp.Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name=django.contrib.auth.models.User),
        ),
    ]
