# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclosetapp', '0002_auto_20170612_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='seller',
            new_name='user',
        ),
    ]
